### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by markovandooren** [faridyagubbayli/binvox#1]
This project contains source code that is copied from a GPL licensed project. As such, this project must also be released under the GPL license, which it is not. 

I am not the author of the original code, but was interested in using the pypi package of this project because the older code is GPL licensed. Upon closer inspection, however, I noticed the license violation.

**Comment by faridyagubbayli** [comment]
Hi Marko, thank you for bringing this up! I was not aware, did my research and you're definitely right. I have updated the license to GPL V3 now. Closing the issue but feel free to re-open it if you think the corrected license is wrong.
